
modLoader="javafml" #mandatory
loaderVersion="[40,)"

license="MIT"
[[mods]] #mandatory
modId="createplus" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Create Plus" #mandatory
credits="Thanks for this example mod goes to Java" #optional
authors="Robocraft999" #optional
description='''

'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.createplus]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.createplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createplus]]
    modId="create"
    mandatory=true
    versionRange="[v0.5.0,)"
    ordering="AFTER"
    side="BOTH"
   
